// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dct.proto

package systemSmartContracts

import (
	bytes "bytes"
	fmt "fmt"
	github_com_Dharitri_org_sme_dharitri_data "github.com/Dharitri-org/sme-dharitri/data"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DCTData struct {
	IssuerAddress []byte        `protobuf:"bytes,1,opt,name=IssuerAddress,proto3" json:"IssuerAddress"`
	TokenName     []byte        `protobuf:"bytes,2,opt,name=TokenName,proto3" json:"TokenName"`
	Mintable      bool          `protobuf:"varint,3,opt,name=Mintable,proto3" json:"Mintable"`
	Burnable      bool          `protobuf:"varint,4,opt,name=Burnable,proto3" json:"Burnable"`
	CanPause      bool          `protobuf:"varint,5,opt,name=CanPause,proto3" json:"CanPause"`
	Paused        bool          `protobuf:"varint,6,opt,name=Paused,proto3" json:"Paused"`
	CanFreeze     bool          `protobuf:"varint,7,opt,name=CanFreeze,proto3" json:"CanFreeze"`
	CanWipe       bool          `protobuf:"varint,8,opt,name=CanWipe,proto3" json:"CanWipe"`
	MintedValue   *math_big.Int `protobuf:"bytes,9,opt,name=MintedValue,proto3,casttypewith=math/big.Int;github.com/Dharitri-org/sme-dharitri/data.BigIntCaster" json:"MintedValue"`
	BurntValue    *math_big.Int `protobuf:"bytes,10,opt,name=BurntValue,proto3,casttypewith=math/big.Int;github.com/Dharitri-org/sme-dharitri/data.BigIntCaster" json:"BurntValue"`
}

func (m *DCTData) Reset()      { *m = DCTData{} }
func (*DCTData) ProtoMessage() {}
func (*DCTData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1cf62b86c79b684, []int{0}
}
func (m *DCTData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DCTData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DCTData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCTData.Merge(m, src)
}
func (m *DCTData) XXX_Size() int {
	return m.Size()
}
func (m *DCTData) XXX_DiscardUnknown() {
	xxx_messageInfo_DCTData.DiscardUnknown(m)
}

var xxx_messageInfo_DCTData proto.InternalMessageInfo

func (m *DCTData) GetIssuerAddress() []byte {
	if m != nil {
		return m.IssuerAddress
	}
	return nil
}

func (m *DCTData) GetTokenName() []byte {
	if m != nil {
		return m.TokenName
	}
	return nil
}

func (m *DCTData) GetMintable() bool {
	if m != nil {
		return m.Mintable
	}
	return false
}

func (m *DCTData) GetBurnable() bool {
	if m != nil {
		return m.Burnable
	}
	return false
}

func (m *DCTData) GetCanPause() bool {
	if m != nil {
		return m.CanPause
	}
	return false
}

func (m *DCTData) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *DCTData) GetCanFreeze() bool {
	if m != nil {
		return m.CanFreeze
	}
	return false
}

func (m *DCTData) GetCanWipe() bool {
	if m != nil {
		return m.CanWipe
	}
	return false
}

func (m *DCTData) GetMintedValue() *math_big.Int {
	if m != nil {
		return m.MintedValue
	}
	return nil
}

func (m *DCTData) GetBurntValue() *math_big.Int {
	if m != nil {
		return m.BurntValue
	}
	return nil
}

type DCTConfig struct {
	OwnerAddress       []byte        `protobuf:"bytes,1,opt,name=OwnerAddress,proto3" json:"OwnerAddress"`
	BaseIssuingCost    *math_big.Int `protobuf:"bytes,2,opt,name=BaseIssuingCost,proto3,casttypewith=math/big.Int;github.com/Dharitri-org/sme-dharitri/data.BigIntCaster" json:"BaseIssuingCost"`
	MinTokenNameLength uint32        `protobuf:"varint,3,opt,name=MinTokenNameLength,proto3" json:"MinTokenNameLength"`
	MaxTokenNameLength uint32        `protobuf:"varint,4,opt,name=MaxTokenNameLength,proto3" json:"MaxTokenNameLength"`
}

func (m *DCTConfig) Reset()      { *m = DCTConfig{} }
func (*DCTConfig) ProtoMessage() {}
func (*DCTConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1cf62b86c79b684, []int{1}
}
func (m *DCTConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DCTConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DCTConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCTConfig.Merge(m, src)
}
func (m *DCTConfig) XXX_Size() int {
	return m.Size()
}
func (m *DCTConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DCTConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DCTConfig proto.InternalMessageInfo

func (m *DCTConfig) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *DCTConfig) GetBaseIssuingCost() *math_big.Int {
	if m != nil {
		return m.BaseIssuingCost
	}
	return nil
}

func (m *DCTConfig) GetMinTokenNameLength() uint32 {
	if m != nil {
		return m.MinTokenNameLength
	}
	return 0
}

func (m *DCTConfig) GetMaxTokenNameLength() uint32 {
	if m != nil {
		return m.MaxTokenNameLength
	}
	return 0
}

func init() {
	proto.RegisterType((*DCTData)(nil), "proto.DCTData")
	proto.RegisterType((*DCTConfig)(nil), "proto.DCTConfig")
}

func init() { proto.RegisterFile("dct.proto", fileDescriptor_c1cf62b86c79b684) }

var fileDescriptor_c1cf62b86c79b684 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe3, 0xb1, 0xad, 0xad, 0xd7, 0x0a, 0xb0, 0x10, 0x8a, 0x38, 0xd8, 0x53, 0x25, 0xa4,
	0x4a, 0xa8, 0xed, 0x01, 0x24, 0x0e, 0x9c, 0x48, 0xaa, 0x49, 0x95, 0xd8, 0x40, 0xa6, 0x0c, 0x69,
	0x37, 0xb7, 0xf1, 0xd2, 0x88, 0xc5, 0x99, 0x6c, 0x47, 0x0c, 0x4e, 0x1c, 0xf8, 0x00, 0x7c, 0x0c,
	0xc4, 0x27, 0xe1, 0xd8, 0x13, 0xea, 0x29, 0xd0, 0xf4, 0x82, 0x72, 0xda, 0x47, 0x40, 0xf1, 0xda,
	0x34, 0x2d, 0x3d, 0xee, 0xe4, 0xff, 0xfb, 0xbd, 0xbf, 0xdf, 0xd3, 0x73, 0x9e, 0x02, 0x6b, 0xde,
	0x48, 0x77, 0x2e, 0x65, 0xa4, 0x23, 0xb4, 0x67, 0x8e, 0x47, 0x6d, 0x3f, 0xd0, 0xe3, 0x78, 0xd8,
	0x19, 0x45, 0x61, 0xd7, 0x8f, 0xfc, 0xa8, 0x6b, 0xf0, 0x30, 0x3e, 0x37, 0x91, 0x09, 0x8c, 0xba,
	0xb9, 0xd5, 0xfc, 0xb5, 0x0b, 0x2b, 0x3d, 0x77, 0xd0, 0x63, 0x9a, 0xa1, 0xe7, 0xb0, 0xd1, 0x57,
	0x2a, 0xe6, 0xf2, 0xa5, 0xe7, 0x49, 0xae, 0x94, 0x0d, 0x0e, 0x41, 0xab, 0xee, 0xdc, 0xcf, 0x12,
	0xb2, 0x9e, 0xa0, 0xeb, 0x21, 0x7a, 0x02, 0x6b, 0x83, 0xe8, 0x03, 0x17, 0x27, 0x2c, 0xe4, 0xf6,
	0x8e, 0xb9, 0xd4, 0xc8, 0x12, 0xb2, 0x82, 0x74, 0x25, 0x51, 0x0b, 0x56, 0x8f, 0x03, 0xa1, 0xd9,
	0xf0, 0x82, 0xdb, 0x77, 0x0e, 0x41, 0xab, 0xea, 0xd4, 0xb3, 0x84, 0x14, 0x8c, 0x16, 0x2a, 0x77,
	0x3a, 0xb1, 0x14, 0xc6, 0xb9, 0xbb, 0x72, 0x2e, 0x19, 0x2d, 0x54, 0xee, 0x74, 0x99, 0x78, 0xc3,
	0x62, 0xc5, 0xed, 0xbd, 0x95, 0x73, 0xc9, 0x68, 0xa1, 0x50, 0x13, 0xee, 0x1b, 0xe1, 0xd9, 0xfb,
	0xc6, 0x07, 0xb3, 0x84, 0x2c, 0x08, 0x5d, 0x9c, 0xf9, 0x38, 0x2e, 0x13, 0x47, 0x92, 0xf3, 0xcf,
	0xdc, 0xae, 0x18, 0x9b, 0x19, 0xa7, 0x80, 0x74, 0x25, 0xd1, 0x63, 0x58, 0x71, 0x99, 0x78, 0x1f,
	0x5c, 0x72, 0xbb, 0x6a, 0xac, 0x07, 0x59, 0x42, 0x96, 0x88, 0x2e, 0x05, 0xba, 0x82, 0x07, 0xf9,
	0x5c, 0xdc, 0x3b, 0x65, 0x17, 0x31, 0xb7, 0x6b, 0xe6, 0x91, 0x4e, 0xb3, 0x84, 0x94, 0xf1, 0x8f,
	0xdf, 0xc4, 0x0d, 0x99, 0x1e, 0x77, 0x87, 0x81, 0xdf, 0xe9, 0x0b, 0xfd, 0xa2, 0xf4, 0x2d, 0x7b,
	0x63, 0x26, 0x03, 0x2d, 0x83, 0x76, 0x24, 0xfd, 0xae, 0x0a, 0x79, 0xdb, 0x5b, 0x80, 0xae, 0xc7,
	0x34, 0xeb, 0x38, 0x81, 0xdf, 0x17, 0xda, 0x65, 0x4a, 0x73, 0x49, 0xcb, 0x35, 0x51, 0x0c, 0x61,
	0xfe, 0x4e, 0xfa, 0xa6, 0x31, 0x34, 0x8d, 0xdf, 0x65, 0x09, 0x29, 0xd1, 0xdb, 0xea, 0x5b, 0x2a,
	0xd9, 0x9c, 0xee, 0xc0, 0x5a, 0xcf, 0x1d, 0xb8, 0x91, 0x38, 0x0f, 0x7c, 0xf4, 0x0c, 0xd6, 0x5f,
	0x7f, 0x14, 0x9b, 0x9b, 0x75, 0x2f, 0x4b, 0xc8, 0x1a, 0xa7, 0x6b, 0x11, 0xfa, 0x0a, 0xe0, 0x5d,
	0x87, 0x29, 0x9e, 0x6f, 0x5b, 0x20, 0x7c, 0x37, 0x52, 0x7a, 0xb1, 0x5e, 0x67, 0x59, 0x42, 0x36,
	0x53, 0xb7, 0x35, 0xc5, 0x66, 0x5d, 0x74, 0x04, 0xd1, 0x71, 0x20, 0x8a, 0x0d, 0x7e, 0xc5, 0x85,
	0xaf, 0xc7, 0x66, 0x77, 0x1b, 0xce, 0xc3, 0x2c, 0x21, 0x5b, 0xb2, 0x74, 0x0b, 0x33, 0x75, 0xd8,
	0xd5, 0x66, 0x9d, 0xdd, 0x52, 0x9d, 0xff, 0xb2, 0x74, 0x0b, 0x73, 0x4e, 0x26, 0x33, 0x6c, 0x4d,
	0x67, 0xd8, 0xba, 0x9e, 0x61, 0xf0, 0x25, 0xc5, 0xe0, 0x7b, 0x8a, 0xc1, 0xcf, 0x14, 0x83, 0x49,
	0x8a, 0xc1, 0x34, 0xc5, 0xe0, 0x4f, 0x8a, 0xc1, 0xdf, 0x14, 0x5b, 0xd7, 0x29, 0x06, 0xdf, 0xe6,
	0xd8, 0x9a, 0xcc, 0xb1, 0x35, 0x9d, 0x63, 0xeb, 0xec, 0x81, 0xfa, 0xa4, 0x34, 0x0f, 0xdf, 0x86,
	0x4c, 0x6a, 0x37, 0x12, 0x5a, 0xb2, 0x91, 0x56, 0xc3, 0x7d, 0xf3, 0x2b, 0x78, 0xfa, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x0c, 0xda, 0xdd, 0x84, 0x4d, 0x04, 0x00, 0x00,
}

func (this *DCTData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DCTData)
	if !ok {
		that2, ok := that.(DCTData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.IssuerAddress, that1.IssuerAddress) {
		return false
	}
	if !bytes.Equal(this.TokenName, that1.TokenName) {
		return false
	}
	if this.Mintable != that1.Mintable {
		return false
	}
	if this.Burnable != that1.Burnable {
		return false
	}
	if this.CanPause != that1.CanPause {
		return false
	}
	if this.Paused != that1.Paused {
		return false
	}
	if this.CanFreeze != that1.CanFreeze {
		return false
	}
	if this.CanWipe != that1.CanWipe {
		return false
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		if !__caster.Equal(this.MintedValue, that1.MintedValue) {
			return false
		}
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		if !__caster.Equal(this.BurntValue, that1.BurntValue) {
			return false
		}
	}
	return true
}
func (this *DCTConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DCTConfig)
	if !ok {
		that2, ok := that.(DCTConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.OwnerAddress, that1.OwnerAddress) {
		return false
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		if !__caster.Equal(this.BaseIssuingCost, that1.BaseIssuingCost) {
			return false
		}
	}
	if this.MinTokenNameLength != that1.MinTokenNameLength {
		return false
	}
	if this.MaxTokenNameLength != that1.MaxTokenNameLength {
		return false
	}
	return true
}
func (this *DCTData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&systemSmartContracts.DCTData{")
	s = append(s, "IssuerAddress: "+fmt.Sprintf("%#v", this.IssuerAddress)+",\n")
	s = append(s, "TokenName: "+fmt.Sprintf("%#v", this.TokenName)+",\n")
	s = append(s, "Mintable: "+fmt.Sprintf("%#v", this.Mintable)+",\n")
	s = append(s, "Burnable: "+fmt.Sprintf("%#v", this.Burnable)+",\n")
	s = append(s, "CanPause: "+fmt.Sprintf("%#v", this.CanPause)+",\n")
	s = append(s, "Paused: "+fmt.Sprintf("%#v", this.Paused)+",\n")
	s = append(s, "CanFreeze: "+fmt.Sprintf("%#v", this.CanFreeze)+",\n")
	s = append(s, "CanWipe: "+fmt.Sprintf("%#v", this.CanWipe)+",\n")
	s = append(s, "MintedValue: "+fmt.Sprintf("%#v", this.MintedValue)+",\n")
	s = append(s, "BurntValue: "+fmt.Sprintf("%#v", this.BurntValue)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DCTConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&systemSmartContracts.DCTConfig{")
	s = append(s, "OwnerAddress: "+fmt.Sprintf("%#v", this.OwnerAddress)+",\n")
	s = append(s, "BaseIssuingCost: "+fmt.Sprintf("%#v", this.BaseIssuingCost)+",\n")
	s = append(s, "MinTokenNameLength: "+fmt.Sprintf("%#v", this.MinTokenNameLength)+",\n")
	s = append(s, "MaxTokenNameLength: "+fmt.Sprintf("%#v", this.MaxTokenNameLength)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringDct(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *DCTData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DCTData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DCTData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		size := __caster.Size(m.BurntValue)
		i -= size
		if _, err := __caster.MarshalTo(m.BurntValue, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDct(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		size := __caster.Size(m.MintedValue)
		i -= size
		if _, err := __caster.MarshalTo(m.MintedValue, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDct(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.CanWipe {
		i--
		if m.CanWipe {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.CanFreeze {
		i--
		if m.CanFreeze {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.CanPause {
		i--
		if m.CanPause {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Burnable {
		i--
		if m.Burnable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Mintable {
		i--
		if m.Mintable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.TokenName) > 0 {
		i -= len(m.TokenName)
		copy(dAtA[i:], m.TokenName)
		i = encodeVarintDct(dAtA, i, uint64(len(m.TokenName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IssuerAddress) > 0 {
		i -= len(m.IssuerAddress)
		copy(dAtA[i:], m.IssuerAddress)
		i = encodeVarintDct(dAtA, i, uint64(len(m.IssuerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DCTConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DCTConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DCTConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTokenNameLength != 0 {
		i = encodeVarintDct(dAtA, i, uint64(m.MaxTokenNameLength))
		i--
		dAtA[i] = 0x20
	}
	if m.MinTokenNameLength != 0 {
		i = encodeVarintDct(dAtA, i, uint64(m.MinTokenNameLength))
		i--
		dAtA[i] = 0x18
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		size := __caster.Size(m.BaseIssuingCost)
		i -= size
		if _, err := __caster.MarshalTo(m.BaseIssuingCost, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDct(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintDct(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDct(dAtA []byte, offset int, v uint64) int {
	offset -= sovDct(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DCTData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IssuerAddress)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	l = len(m.TokenName)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	if m.Mintable {
		n += 2
	}
	if m.Burnable {
		n += 2
	}
	if m.CanPause {
		n += 2
	}
	if m.Paused {
		n += 2
	}
	if m.CanFreeze {
		n += 2
	}
	if m.CanWipe {
		n += 2
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		l = __caster.Size(m.MintedValue)
		n += 1 + l + sovDct(uint64(l))
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		l = __caster.Size(m.BurntValue)
		n += 1 + l + sovDct(uint64(l))
	}
	return n
}

func (m *DCTConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		l = __caster.Size(m.BaseIssuingCost)
		n += 1 + l + sovDct(uint64(l))
	}
	if m.MinTokenNameLength != 0 {
		n += 1 + sovDct(uint64(m.MinTokenNameLength))
	}
	if m.MaxTokenNameLength != 0 {
		n += 1 + sovDct(uint64(m.MaxTokenNameLength))
	}
	return n
}

func sovDct(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDct(x uint64) (n int) {
	return sovDct(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DCTData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DCTData{`,
		`IssuerAddress:` + fmt.Sprintf("%v", this.IssuerAddress) + `,`,
		`TokenName:` + fmt.Sprintf("%v", this.TokenName) + `,`,
		`Mintable:` + fmt.Sprintf("%v", this.Mintable) + `,`,
		`Burnable:` + fmt.Sprintf("%v", this.Burnable) + `,`,
		`CanPause:` + fmt.Sprintf("%v", this.CanPause) + `,`,
		`Paused:` + fmt.Sprintf("%v", this.Paused) + `,`,
		`CanFreeze:` + fmt.Sprintf("%v", this.CanFreeze) + `,`,
		`CanWipe:` + fmt.Sprintf("%v", this.CanWipe) + `,`,
		`MintedValue:` + fmt.Sprintf("%v", this.MintedValue) + `,`,
		`BurntValue:` + fmt.Sprintf("%v", this.BurntValue) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DCTConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DCTConfig{`,
		`OwnerAddress:` + fmt.Sprintf("%v", this.OwnerAddress) + `,`,
		`BaseIssuingCost:` + fmt.Sprintf("%v", this.BaseIssuingCost) + `,`,
		`MinTokenNameLength:` + fmt.Sprintf("%v", this.MinTokenNameLength) + `,`,
		`MaxTokenNameLength:` + fmt.Sprintf("%v", this.MaxTokenNameLength) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringDct(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DCTData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DCTData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DCTData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerAddress = append(m.IssuerAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.IssuerAddress == nil {
				m.IssuerAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenName", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenName = append(m.TokenName[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenName == nil {
				m.TokenName = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mintable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mintable = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Burnable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Burnable = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanPause", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanPause = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanFreeze", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanFreeze = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanWipe", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanWipe = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.MintedValue = tmp
				}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurntValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.BurntValue = tmp
				}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DCTConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DCTConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DCTConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = append(m.OwnerAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.OwnerAddress == nil {
				m.OwnerAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseIssuingCost", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.BaseIssuingCost = tmp
				}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTokenNameLength", wireType)
			}
			m.MinTokenNameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinTokenNameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTokenNameLength", wireType)
			}
			m.MaxTokenNameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTokenNameLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDct(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDct
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDct
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDct
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDct
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDct        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDct          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDct = fmt.Errorf("proto: unexpected end of group")
)
