language: go

go: "1.13"

os:
- linux
- osx

arch:
- amd64
- arm64

osx_image: xcode11.3

before_script:
- APP_VER=$(git describe --tags --long --dirty)
- APP_VER_SHORT=$(git describe --tags)
- GOOS=$(go env GOOS)
- GOARCH=$(go env GOARCH)
- ARCHIVE="dharitri_""$APP_VER_SHORT""_""$GOOS""_""$GOARCH"".tgz"

script:
- MOA_PACKAGE=node
- cd $TRAVIS_BUILD_DIR/cmd/$MOA_PACKAGE
- go build -o "$TRAVIS_BUILD_DIR/build/$MOA_PACKAGE" -a -i -ldflags="-X main.appVersion=$APP_VER"
- MOA_PACKAGE=keygenerator
- cd $TRAVIS_BUILD_DIR/cmd/$MOA_PACKAGE
- go build -o "$TRAVIS_BUILD_DIR/build/$MOA_PACKAGE" -a -i -ldflags="-X main.appVersion=$APP_VER"
- MOA_PACKAGE=logviewer
- cd $TRAVIS_BUILD_DIR/cmd/$MOA_PACKAGE
- go build -o "$TRAVIS_BUILD_DIR/build/$MOA_PACKAGE" -a -i -ldflags="-X main.appVersion=$APP_VER"
- MOA_PACKAGE=termui
- cd $TRAVIS_BUILD_DIR/cmd/$MOA_PACKAGE
- go build -o "$TRAVIS_BUILD_DIR/build/$MOA_PACKAGE" -a -i -ldflags="-X main.appVersion=$APP_VER"
- cd $TRAVIS_BUILD_DIR 
- CORE_PATH=$TRAVIS_BUILD_DIR/build/core make core

- GOOS=$(go env GOOS)
- GOARCH=$(go env GOARCH)
- cd $TRAVIS_BUILD_DIR
- CORE_VERSION=$(cat go.mod | grep core | sed 's/^.*core-wasm-vm *//')
- if [[ "$GOOS" == linux && "$GOARCH" == amd64 ]]; then
    cp -f $GOPATH/pkg/mod/github.com/\!dharitri\!org/sme-core-vm-go@$CORE_VERSION/wasmer/libwasmer_linux_amd64.so $TRAVIS_BUILD_DIR/build;
  fi
- if [[ "$GOOS" == linux && "$GOARCH" == arm64 ]]; then
    cp -f $GOPATH/pkg/mod/github.com/\!dharitri\!org/sme-core-vm-go@$CORE_VERSION/wasmer/libwasmer_linux_arm64.so $TRAVIS_BUILD_DIR/build;
  fi
- if [[ "$GOOS" == darwin && "$GOARCH" == amd64 ]]; then
    cp -f $GOPATH/pkg/mod/github.com/\!dharitri\!org/sme-core-vm-go@$CORE_VERSION/wasmer/libwasmer_darwin_amd64.dylib $TRAVIS_BUILD_DIR/build;
  fi

before_deploy:
- cd "$TRAVIS_BUILD_DIR/build"
- tar czvf "$TRAVIS_BUILD_DIR/$ARCHIVE" *

after_deploy:
- rm -rf "$TRAVIS_BUILD_DIR/build"
- rm -rf "$TRAVIS_BUILD_DIR/$ARCHIVE"

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: "$TRAVIS_BUILD_DIR/$ARCHIVE"
  draft: true
  on:
    tags: true
