// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: validatorInfo.proto

package state

import (
	bytes "bytes"
	encoding_binary "encoding/binary"
	fmt "fmt"
	github_com_Dharitri_org_sme_dharitri_data "github.com/Dharitri-org/sme-dharitri/data"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorInfo represents the data regarding a validator that is verified by the metaNodes
type ValidatorInfo struct {
	PublicKey                  []byte        `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	ShardId                    uint32        `protobuf:"varint,2,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	List                       string        `protobuf:"bytes,3,opt,name=List,proto3" json:"List,omitempty"`
	Index                      uint32        `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	TempRating                 uint32        `protobuf:"varint,5,opt,name=TempRating,proto3" json:"TempRating,omitempty"`
	Rating                     uint32        `protobuf:"varint,6,opt,name=Rating,proto3" json:"Rating,omitempty"`
	RatingModifier             float32       `protobuf:"fixed32,7,opt,name=RatingModifier,proto3" json:"RatingModifier,omitempty"`
	RewardAddress              []byte        `protobuf:"bytes,8,opt,name=RewardAddress,proto3" json:"RewardAddress,omitempty"`
	LeaderSuccess              uint32        `protobuf:"varint,9,opt,name=LeaderSuccess,proto3" json:"LeaderSuccess,omitempty"`
	LeaderFailure              uint32        `protobuf:"varint,10,opt,name=LeaderFailure,proto3" json:"LeaderFailure,omitempty"`
	ValidatorSuccess           uint32        `protobuf:"varint,11,opt,name=ValidatorSuccess,proto3" json:"ValidatorSuccess,omitempty"`
	ValidatorFailure           uint32        `protobuf:"varint,12,opt,name=ValidatorFailure,proto3" json:"ValidatorFailure,omitempty"`
	NumSelectedInSuccessBlocks uint32        `protobuf:"varint,13,opt,name=NumSelectedInSuccessBlocks,proto3" json:"NumSelectedInSuccessBlocks,omitempty"`
	AccumulatedFees            *math_big.Int `protobuf:"bytes,14,opt,name=AccumulatedFees,proto3,casttypewith=math/big.Int;github.com/Dharitri-org/sme-dharitri/data.BigIntCaster" json:"AccumulatedFees,omitempty"`
	TotalLeaderSuccess         uint32        `protobuf:"varint,15,opt,name=TotalLeaderSuccess,proto3" json:"TotalLeaderSuccess,omitempty"`
	TotalLeaderFailure         uint32        `protobuf:"varint,16,opt,name=TotalLeaderFailure,proto3" json:"TotalLeaderFailure,omitempty"`
	TotalValidatorSuccess      uint32        `protobuf:"varint,17,opt,name=TotalValidatorSuccess,proto3" json:"TotalValidatorSuccess,omitempty"`
	TotalValidatorFailure      uint32        `protobuf:"varint,18,opt,name=TotalValidatorFailure,proto3" json:"TotalValidatorFailure,omitempty"`
}

func (m *ValidatorInfo) Reset()      { *m = ValidatorInfo{} }
func (*ValidatorInfo) ProtoMessage() {}
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf9cdc082f0b2ec2, []int{0}
}
func (m *ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorInfo.Merge(m, src)
}
func (m *ValidatorInfo) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorInfo proto.InternalMessageInfo

func (m *ValidatorInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ValidatorInfo) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ValidatorInfo) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *ValidatorInfo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ValidatorInfo) GetTempRating() uint32 {
	if m != nil {
		return m.TempRating
	}
	return 0
}

func (m *ValidatorInfo) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *ValidatorInfo) GetRatingModifier() float32 {
	if m != nil {
		return m.RatingModifier
	}
	return 0
}

func (m *ValidatorInfo) GetRewardAddress() []byte {
	if m != nil {
		return m.RewardAddress
	}
	return nil
}

func (m *ValidatorInfo) GetLeaderSuccess() uint32 {
	if m != nil {
		return m.LeaderSuccess
	}
	return 0
}

func (m *ValidatorInfo) GetLeaderFailure() uint32 {
	if m != nil {
		return m.LeaderFailure
	}
	return 0
}

func (m *ValidatorInfo) GetValidatorSuccess() uint32 {
	if m != nil {
		return m.ValidatorSuccess
	}
	return 0
}

func (m *ValidatorInfo) GetValidatorFailure() uint32 {
	if m != nil {
		return m.ValidatorFailure
	}
	return 0
}

func (m *ValidatorInfo) GetNumSelectedInSuccessBlocks() uint32 {
	if m != nil {
		return m.NumSelectedInSuccessBlocks
	}
	return 0
}

func (m *ValidatorInfo) GetAccumulatedFees() *math_big.Int {
	if m != nil {
		return m.AccumulatedFees
	}
	return nil
}

func (m *ValidatorInfo) GetTotalLeaderSuccess() uint32 {
	if m != nil {
		return m.TotalLeaderSuccess
	}
	return 0
}

func (m *ValidatorInfo) GetTotalLeaderFailure() uint32 {
	if m != nil {
		return m.TotalLeaderFailure
	}
	return 0
}

func (m *ValidatorInfo) GetTotalValidatorSuccess() uint32 {
	if m != nil {
		return m.TotalValidatorSuccess
	}
	return 0
}

func (m *ValidatorInfo) GetTotalValidatorFailure() uint32 {
	if m != nil {
		return m.TotalValidatorFailure
	}
	return 0
}

// ShardValidatorInfo represents the data regarding a validator that is stored in the PeerMiniblocks
type ShardValidatorInfo struct {
	PublicKey  []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	ShardId    uint32 `protobuf:"varint,2,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	List       string `protobuf:"bytes,3,opt,name=List,proto3" json:"List,omitempty"`
	Index      uint32 `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	TempRating uint32 `protobuf:"varint,5,opt,name=TempRating,proto3" json:"TempRating,omitempty"`
}

func (m *ShardValidatorInfo) Reset()      { *m = ShardValidatorInfo{} }
func (*ShardValidatorInfo) ProtoMessage() {}
func (*ShardValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf9cdc082f0b2ec2, []int{1}
}
func (m *ShardValidatorInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ShardValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardValidatorInfo.Merge(m, src)
}
func (m *ShardValidatorInfo) XXX_Size() int {
	return m.Size()
}
func (m *ShardValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShardValidatorInfo proto.InternalMessageInfo

func (m *ShardValidatorInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ShardValidatorInfo) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ShardValidatorInfo) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *ShardValidatorInfo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ShardValidatorInfo) GetTempRating() uint32 {
	if m != nil {
		return m.TempRating
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorInfo)(nil), "proto.ValidatorInfo")
	proto.RegisterType((*ShardValidatorInfo)(nil), "proto.ShardValidatorInfo")
}

func init() { proto.RegisterFile("validatorInfo.proto", fileDescriptor_bf9cdc082f0b2ec2) }

var fileDescriptor_bf9cdc082f0b2ec2 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x3d, 0xa5, 0x49, 0xc9, 0xd0, 0xb4, 0x65, 0xb8, 0x68, 0x54, 0xa1, 0x21, 0xaa, 0x10,
	0x8a, 0x90, 0x92, 0x2c, 0x60, 0x87, 0x04, 0x6a, 0x8a, 0x8a, 0x2c, 0x0a, 0x42, 0x4e, 0xc5, 0x82,
	0xdd, 0xd8, 0x33, 0x71, 0x46, 0xd8, 0x9e, 0x32, 0x1e, 0x73, 0xd9, 0xf1, 0x08, 0xac, 0x58, 0xf0,
	0x04, 0x88, 0x27, 0x61, 0x99, 0x65, 0x76, 0x10, 0x67, 0xc3, 0xb2, 0x8f, 0x80, 0x72, 0x62, 0xd3,
	0xdc, 0xc4, 0x9a, 0x55, 0xce, 0xf9, 0xcf, 0x77, 0xfe, 0x89, 0x7f, 0xcd, 0xe0, 0x6b, 0xef, 0x78,
	0xa4, 0x04, 0xb7, 0xda, 0xb8, 0x49, 0x5f, 0xb7, 0xcf, 0x8c, 0xb6, 0x9a, 0x54, 0xe0, 0x67, 0xbf,
	0x15, 0x2a, 0x3b, 0xc8, 0xfc, 0x76, 0xa0, 0xe3, 0x4e, 0xa8, 0x43, 0xdd, 0x01, 0xd9, 0xcf, 0xfa,
	0xd0, 0x41, 0x03, 0xd5, 0x6c, 0xeb, 0xe0, 0x6b, 0x15, 0xd7, 0x5f, 0xcd, 0xbb, 0x91, 0x5b, 0xb8,
	0xf6, 0x32, 0xf3, 0x23, 0x15, 0x3c, 0x93, 0x1f, 0x29, 0x6a, 0xa0, 0xe6, 0xb6, 0x77, 0x21, 0x10,
	0x8a, 0xb7, 0x7a, 0x03, 0x6e, 0x84, 0x2b, 0xe8, 0x46, 0x03, 0x35, 0xeb, 0x5e, 0xd9, 0x12, 0x82,
	0x37, 0x4f, 0x54, 0x6a, 0xe9, 0xa5, 0x06, 0x6a, 0xd6, 0x3c, 0xa8, 0xc9, 0x75, 0x5c, 0x71, 0x13,
	0x21, 0x3f, 0xd0, 0x4d, 0x60, 0x67, 0x0d, 0x61, 0x18, 0x9f, 0xca, 0xf8, 0xcc, 0xe3, 0x56, 0x25,
	0x21, 0xad, 0xc0, 0x68, 0x4e, 0x21, 0x37, 0x71, 0xb5, 0x98, 0x55, 0x61, 0x56, 0x74, 0xe4, 0x2e,
	0xde, 0x99, 0x55, 0xcf, 0xb5, 0x50, 0x7d, 0x25, 0x0d, 0xdd, 0x6a, 0xa0, 0xe6, 0x86, 0xb7, 0xa4,
	0x92, 0x3b, 0xb8, 0xee, 0xc9, 0xf7, 0xdc, 0x88, 0x43, 0x21, 0x8c, 0x4c, 0x53, 0x7a, 0x19, 0xbe,
	0x62, 0x51, 0x9c, 0x52, 0x27, 0x92, 0x0b, 0x69, 0x7a, 0x59, 0x10, 0x4c, 0xa9, 0x1a, 0x1c, 0xb6,
	0x28, 0x5e, 0x50, 0xc7, 0x5c, 0x45, 0x99, 0x91, 0x14, 0xcf, 0x53, 0x85, 0x48, 0xee, 0xe1, 0xbd,
	0xbf, 0x21, 0x96, 0x76, 0x57, 0x00, 0x5c, 0xd1, 0x17, 0xd8, 0xd2, 0x74, 0x7b, 0x89, 0x2d, 0x7d,
	0x1f, 0xe1, 0xfd, 0x17, 0x59, 0xdc, 0x93, 0x91, 0x0c, 0xac, 0x14, 0x6e, 0x52, 0x78, 0x74, 0x23,
	0x1d, 0xbc, 0x49, 0x69, 0x1d, 0xb6, 0xfe, 0x41, 0x90, 0xb7, 0x78, 0xf7, 0x30, 0x08, 0xb2, 0x38,
	0x8b, 0xb8, 0x95, 0xe2, 0x58, 0xca, 0x94, 0xee, 0x4c, 0xb3, 0xe8, 0x3e, 0xfd, 0xfe, 0xf3, 0xf6,
	0x51, 0xcc, 0xed, 0xa0, 0xe3, 0xab, 0xb0, 0xed, 0x26, 0xf6, 0xe1, 0xdc, 0xb5, 0x79, 0x32, 0xe0,
	0x46, 0x59, 0xa3, 0x5a, 0xda, 0x84, 0x9d, 0x34, 0x96, 0x2d, 0x51, 0x08, 0x1d, 0xc1, 0x2d, 0x6f,
	0x77, 0x55, 0xe8, 0x26, 0xf6, 0x88, 0xa7, 0x56, 0x1a, 0x6f, 0xd9, 0x9f, 0xb4, 0x31, 0x39, 0xd5,
	0x96, 0x47, 0x8b, 0xd9, 0xee, 0xc2, 0x5f, 0x5d, 0x33, 0x59, 0xe2, 0xcb, 0x40, 0xf6, 0x56, 0xf8,
	0x32, 0x92, 0x07, 0xf8, 0x06, 0xa8, 0x2b, 0x79, 0x5f, 0x85, 0x95, 0xf5, 0xc3, 0xd5, 0xad, 0xf2,
	0x20, 0xb2, 0x6e, 0xab, 0x18, 0x1e, 0x7c, 0x41, 0x98, 0xc0, 0xf5, 0xfe, 0xcf, 0x5e, 0x48, 0xf7,
	0xf1, 0x70, 0xcc, 0x9c, 0xd1, 0x98, 0x39, 0xe7, 0x63, 0x86, 0x3e, 0xe5, 0x0c, 0x7d, 0xcb, 0x19,
	0xfa, 0x91, 0x33, 0x34, 0xcc, 0x19, 0x1a, 0xe5, 0x0c, 0xfd, 0xca, 0x19, 0xfa, 0x9d, 0x33, 0xe7,
	0x3c, 0x67, 0xe8, 0xf3, 0x84, 0x39, 0xc3, 0x09, 0x73, 0x46, 0x13, 0xe6, 0xbc, 0xae, 0xa4, 0x96,
	0x5b, 0xe9, 0x57, 0xe1, 0xf5, 0xdf, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x72, 0x08, 0x9a,
	0x4a, 0x04, 0x00, 0x00,
}

func (this *ValidatorInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorInfo)
	if !ok {
		that2, ok := that.(ValidatorInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if this.List != that1.List {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if this.TempRating != that1.TempRating {
		return false
	}
	if this.Rating != that1.Rating {
		return false
	}
	if this.RatingModifier != that1.RatingModifier {
		return false
	}
	if !bytes.Equal(this.RewardAddress, that1.RewardAddress) {
		return false
	}
	if this.LeaderSuccess != that1.LeaderSuccess {
		return false
	}
	if this.LeaderFailure != that1.LeaderFailure {
		return false
	}
	if this.ValidatorSuccess != that1.ValidatorSuccess {
		return false
	}
	if this.ValidatorFailure != that1.ValidatorFailure {
		return false
	}
	if this.NumSelectedInSuccessBlocks != that1.NumSelectedInSuccessBlocks {
		return false
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		if !__caster.Equal(this.AccumulatedFees, that1.AccumulatedFees) {
			return false
		}
	}
	if this.TotalLeaderSuccess != that1.TotalLeaderSuccess {
		return false
	}
	if this.TotalLeaderFailure != that1.TotalLeaderFailure {
		return false
	}
	if this.TotalValidatorSuccess != that1.TotalValidatorSuccess {
		return false
	}
	if this.TotalValidatorFailure != that1.TotalValidatorFailure {
		return false
	}
	return true
}
func (this *ShardValidatorInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ShardValidatorInfo)
	if !ok {
		that2, ok := that.(ShardValidatorInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if this.List != that1.List {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if this.TempRating != that1.TempRating {
		return false
	}
	return true
}
func (this *ValidatorInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 22)
	s = append(s, "&state.ValidatorInfo{")
	s = append(s, "PublicKey: "+fmt.Sprintf("%#v", this.PublicKey)+",\n")
	s = append(s, "ShardId: "+fmt.Sprintf("%#v", this.ShardId)+",\n")
	s = append(s, "List: "+fmt.Sprintf("%#v", this.List)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "TempRating: "+fmt.Sprintf("%#v", this.TempRating)+",\n")
	s = append(s, "Rating: "+fmt.Sprintf("%#v", this.Rating)+",\n")
	s = append(s, "RatingModifier: "+fmt.Sprintf("%#v", this.RatingModifier)+",\n")
	s = append(s, "RewardAddress: "+fmt.Sprintf("%#v", this.RewardAddress)+",\n")
	s = append(s, "LeaderSuccess: "+fmt.Sprintf("%#v", this.LeaderSuccess)+",\n")
	s = append(s, "LeaderFailure: "+fmt.Sprintf("%#v", this.LeaderFailure)+",\n")
	s = append(s, "ValidatorSuccess: "+fmt.Sprintf("%#v", this.ValidatorSuccess)+",\n")
	s = append(s, "ValidatorFailure: "+fmt.Sprintf("%#v", this.ValidatorFailure)+",\n")
	s = append(s, "NumSelectedInSuccessBlocks: "+fmt.Sprintf("%#v", this.NumSelectedInSuccessBlocks)+",\n")
	s = append(s, "AccumulatedFees: "+fmt.Sprintf("%#v", this.AccumulatedFees)+",\n")
	s = append(s, "TotalLeaderSuccess: "+fmt.Sprintf("%#v", this.TotalLeaderSuccess)+",\n")
	s = append(s, "TotalLeaderFailure: "+fmt.Sprintf("%#v", this.TotalLeaderFailure)+",\n")
	s = append(s, "TotalValidatorSuccess: "+fmt.Sprintf("%#v", this.TotalValidatorSuccess)+",\n")
	s = append(s, "TotalValidatorFailure: "+fmt.Sprintf("%#v", this.TotalValidatorFailure)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ShardValidatorInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&state.ShardValidatorInfo{")
	s = append(s, "PublicKey: "+fmt.Sprintf("%#v", this.PublicKey)+",\n")
	s = append(s, "ShardId: "+fmt.Sprintf("%#v", this.ShardId)+",\n")
	s = append(s, "List: "+fmt.Sprintf("%#v", this.List)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "TempRating: "+fmt.Sprintf("%#v", this.TempRating)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringValidatorInfo(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ValidatorInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalValidatorFailure != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TotalValidatorFailure))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.TotalValidatorSuccess != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TotalValidatorSuccess))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.TotalLeaderFailure != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TotalLeaderFailure))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.TotalLeaderSuccess != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TotalLeaderSuccess))
		i--
		dAtA[i] = 0x78
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		size := __caster.Size(m.AccumulatedFees)
		i -= size
		if _, err := __caster.MarshalTo(m.AccumulatedFees, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintValidatorInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if m.NumSelectedInSuccessBlocks != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.NumSelectedInSuccessBlocks))
		i--
		dAtA[i] = 0x68
	}
	if m.ValidatorFailure != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.ValidatorFailure))
		i--
		dAtA[i] = 0x60
	}
	if m.ValidatorSuccess != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.ValidatorSuccess))
		i--
		dAtA[i] = 0x58
	}
	if m.LeaderFailure != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.LeaderFailure))
		i--
		dAtA[i] = 0x50
	}
	if m.LeaderSuccess != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.LeaderSuccess))
		i--
		dAtA[i] = 0x48
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintValidatorInfo(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x42
	}
	if m.RatingModifier != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.RatingModifier))))
		i--
		dAtA[i] = 0x3d
	}
	if m.Rating != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.Rating))
		i--
		dAtA[i] = 0x30
	}
	if m.TempRating != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TempRating))
		i--
		dAtA[i] = 0x28
	}
	if m.Index != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if len(m.List) > 0 {
		i -= len(m.List)
		copy(dAtA[i:], m.List)
		i = encodeVarintValidatorInfo(dAtA, i, uint64(len(m.List)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ShardId != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintValidatorInfo(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ShardValidatorInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardValidatorInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShardValidatorInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TempRating != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.TempRating))
		i--
		dAtA[i] = 0x28
	}
	if m.Index != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x20
	}
	if len(m.List) > 0 {
		i -= len(m.List)
		copy(dAtA[i:], m.List)
		i = encodeVarintValidatorInfo(dAtA, i, uint64(len(m.List)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ShardId != 0 {
		i = encodeVarintValidatorInfo(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintValidatorInfo(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintValidatorInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovValidatorInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.ShardId != 0 {
		n += 1 + sovValidatorInfo(uint64(m.ShardId))
	}
	l = len(m.List)
	if l > 0 {
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovValidatorInfo(uint64(m.Index))
	}
	if m.TempRating != 0 {
		n += 1 + sovValidatorInfo(uint64(m.TempRating))
	}
	if m.Rating != 0 {
		n += 1 + sovValidatorInfo(uint64(m.Rating))
	}
	if m.RatingModifier != 0 {
		n += 5
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.LeaderSuccess != 0 {
		n += 1 + sovValidatorInfo(uint64(m.LeaderSuccess))
	}
	if m.LeaderFailure != 0 {
		n += 1 + sovValidatorInfo(uint64(m.LeaderFailure))
	}
	if m.ValidatorSuccess != 0 {
		n += 1 + sovValidatorInfo(uint64(m.ValidatorSuccess))
	}
	if m.ValidatorFailure != 0 {
		n += 1 + sovValidatorInfo(uint64(m.ValidatorFailure))
	}
	if m.NumSelectedInSuccessBlocks != 0 {
		n += 1 + sovValidatorInfo(uint64(m.NumSelectedInSuccessBlocks))
	}
	{
		__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
		l = __caster.Size(m.AccumulatedFees)
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.TotalLeaderSuccess != 0 {
		n += 1 + sovValidatorInfo(uint64(m.TotalLeaderSuccess))
	}
	if m.TotalLeaderFailure != 0 {
		n += 2 + sovValidatorInfo(uint64(m.TotalLeaderFailure))
	}
	if m.TotalValidatorSuccess != 0 {
		n += 2 + sovValidatorInfo(uint64(m.TotalValidatorSuccess))
	}
	if m.TotalValidatorFailure != 0 {
		n += 2 + sovValidatorInfo(uint64(m.TotalValidatorFailure))
	}
	return n
}

func (m *ShardValidatorInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.ShardId != 0 {
		n += 1 + sovValidatorInfo(uint64(m.ShardId))
	}
	l = len(m.List)
	if l > 0 {
		n += 1 + l + sovValidatorInfo(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovValidatorInfo(uint64(m.Index))
	}
	if m.TempRating != 0 {
		n += 1 + sovValidatorInfo(uint64(m.TempRating))
	}
	return n
}

func sovValidatorInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValidatorInfo(x uint64) (n int) {
	return sovValidatorInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ValidatorInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ValidatorInfo{`,
		`PublicKey:` + fmt.Sprintf("%v", this.PublicKey) + `,`,
		`ShardId:` + fmt.Sprintf("%v", this.ShardId) + `,`,
		`List:` + fmt.Sprintf("%v", this.List) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`TempRating:` + fmt.Sprintf("%v", this.TempRating) + `,`,
		`Rating:` + fmt.Sprintf("%v", this.Rating) + `,`,
		`RatingModifier:` + fmt.Sprintf("%v", this.RatingModifier) + `,`,
		`RewardAddress:` + fmt.Sprintf("%v", this.RewardAddress) + `,`,
		`LeaderSuccess:` + fmt.Sprintf("%v", this.LeaderSuccess) + `,`,
		`LeaderFailure:` + fmt.Sprintf("%v", this.LeaderFailure) + `,`,
		`ValidatorSuccess:` + fmt.Sprintf("%v", this.ValidatorSuccess) + `,`,
		`ValidatorFailure:` + fmt.Sprintf("%v", this.ValidatorFailure) + `,`,
		`NumSelectedInSuccessBlocks:` + fmt.Sprintf("%v", this.NumSelectedInSuccessBlocks) + `,`,
		`AccumulatedFees:` + fmt.Sprintf("%v", this.AccumulatedFees) + `,`,
		`TotalLeaderSuccess:` + fmt.Sprintf("%v", this.TotalLeaderSuccess) + `,`,
		`TotalLeaderFailure:` + fmt.Sprintf("%v", this.TotalLeaderFailure) + `,`,
		`TotalValidatorSuccess:` + fmt.Sprintf("%v", this.TotalValidatorSuccess) + `,`,
		`TotalValidatorFailure:` + fmt.Sprintf("%v", this.TotalValidatorFailure) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ShardValidatorInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ShardValidatorInfo{`,
		`PublicKey:` + fmt.Sprintf("%v", this.PublicKey) + `,`,
		`ShardId:` + fmt.Sprintf("%v", this.ShardId) + `,`,
		`List:` + fmt.Sprintf("%v", this.List) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`TempRating:` + fmt.Sprintf("%v", this.TempRating) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringValidatorInfo(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ValidatorInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TempRating", wireType)
			}
			m.TempRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TempRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rating", wireType)
			}
			m.Rating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatingModifier", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.RatingModifier = float32(math.Float32frombits(v))
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = append(m.RewardAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.RewardAddress == nil {
				m.RewardAddress = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderSuccess", wireType)
			}
			m.LeaderSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderFailure", wireType)
			}
			m.LeaderFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSuccess", wireType)
			}
			m.ValidatorSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorFailure", wireType)
			}
			m.ValidatorFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSelectedInSuccessBlocks", wireType)
			}
			m.NumSelectedInSuccessBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSelectedInSuccessBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulatedFees", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_Dharitri_org_sme_dharitri_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.AccumulatedFees = tmp
				}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLeaderSuccess", wireType)
			}
			m.TotalLeaderSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalLeaderSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLeaderFailure", wireType)
			}
			m.TotalLeaderFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalLeaderFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValidatorSuccess", wireType)
			}
			m.TotalValidatorSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalValidatorSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValidatorFailure", wireType)
			}
			m.TotalValidatorFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalValidatorFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShardValidatorInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardValidatorInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardValidatorInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TempRating", wireType)
			}
			m.TempRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TempRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValidatorInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValidatorInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValidatorInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValidatorInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValidatorInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValidatorInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValidatorInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValidatorInfo = fmt.Errorf("proto: unexpected end of group")
)
